// Thin TS wrapper over the Rust→WASM compiler — the one compile core shared by the
// embed, the interactive viewer, and the playground.
//
// The WASM module is initialized once. Two init paths share the single module:
//   • ensureReady()      — the apps: lazy async init(), fetching the sibling .wasm
//                          asset Vite emits (new URL('..._bg.wasm', import.meta.url)).
//   • initFromBytes(b)   — the single-file embed: synchronous init from WASM bytes
//                          inlined into the bundle, so no extra network request runs.
//
// `../../pkg/` is generated by `wasm-pack` (see `npm run wasm:dev`). Until you have
// run a build at least once, the editor will not find these types — that's expected.
import init, { compile, initSync } from "../../pkg/xsvg_wasm.js";

let ready: Promise<unknown> | null = null;

function ensureReady(): Promise<unknown> {
  if (!ready) ready = init();
  return ready;
}

/**
 * Pre-initialize the WASM synchronously from raw module bytes. Used by the embed
 * bundle, which inlines the `.wasm` so a single `<script>` is fully self-contained.
 * A no-op if the module is already initialized.
 */
export function initFromBytes(bytes: Uint8Array): void {
  if (ready) return;
  initSync({ module: bytes });
  ready = Promise.resolve();
}

// Font metrics for text layout — the browser implementation of the core's
// `Measurer` seam. The Rust compiler calls this back synchronously during
// lowering (e.g. for `inline-size` wrapping and `<x:textbox>` shrink-to-fit).
let measureCtx: CanvasRenderingContext2D | null = null;
function ctx(): CanvasRenderingContext2D | null {
  if (!measureCtx) measureCtx = document.createElement("canvas").getContext("2d");
  return measureCtx;
}

function measure(text: string, fontCss: string): number {
  const c = ctx();
  if (!c) return 0;
  c.font = fontCss;
  return c.measureText(text).width;
}

// Vertical font metrics at the given font: [ascent, descent, capHeight, xHeight].
function metrics(fontCss: string): number[] {
  const c = ctx();
  if (!c) return [];
  c.font = fontCss;
  const box = c.measureText("Hg");
  const cap = c.measureText("H");
  const ex = c.measureText("x");
  return [
    box.fontBoundingBoxAscent,
    box.fontBoundingBoxDescent,
    cap.actualBoundingBoxAscent,
    ex.actualBoundingBoxAscent,
  ];
}

// Shape rasterizer — the browser implementation of the core's `Shaper` seam, used
// by `<x:textbox in="#shape">` to flow text inside a curved outline. Curve
// flattening + inside-testing are deferred to the browser (`getBBox` +
// `isPointInFill`) on a hidden offscreen <svg> probe.
const SVG_NS = "http://www.w3.org/2000/svg";
let probePath: SVGPathElement | null = null;
function probe(): SVGPathElement {
  if (!probePath) {
    const svg = document.createElementNS(SVG_NS, "svg");
    // rendered but off-screen: getBBox needs layout (display:none returns zeros)
    svg.setAttribute("style", "position:absolute;left:-99999px;top:0;overflow:hidden");
    probePath = document.createElementNS(SVG_NS, "path");
    svg.appendChild(probePath);
    document.body.appendChild(svg);
  }
  return probePath;
}

// Rasterize a filled path `d` into [minX, minY, w, h, rowH, l0,r0, l1,r1, …] — one
// inside [left,right] span per ~rowH-tall row (NaN pair if that row is empty).
// Exported so the fixture generator (dev/fixtures.ts) can reuse the exact browser path.
export function rasterize(d: string, rowH: number): number[] {
  const p = probe();
  p.setAttribute("d", d);
  let bb: DOMRect;
  try {
    bb = p.getBBox();
  } catch {
    return [];
  }
  if (!(bb.width > 0 && bb.height > 0 && rowH > 0)) return [];

  const rows = Math.max(1, Math.ceil(bb.height / rowH));
  const rh = bb.height / rows;
  const xSteps = Math.max(24, Math.min(400, Math.ceil(bb.width)));
  const dx = bb.width / xSteps;
  const out: number[] = [bb.x, bb.y, bb.width, bb.height, rh];
  const pt = new DOMPoint(0, 0);

  for (let r = 0; r < rows; r++) {
    pt.y = bb.y + (r + 0.5) * rh;
    let left = NaN;
    let right = NaN;
    for (let i = 0; i <= xSteps; i++) {
      pt.x = bb.x + i * dx;
      if (p.isPointInFill(pt)) {
        if (Number.isNaN(left)) left = pt.x;
        right = pt.x;
      }
    }
    out.push(left, right);
  }
  return out;
}

// Glyph outliner — the browser implementation of the core's `GlyphOutliner` seam.
// "Create outlines" (`x:outline`/`outline="true"`) turns a text run into a <path>;
// opentype.js needs the font *bytes*, keyed by family. A family with no registered
// font returns "" → the compiler falls back to live <text>, so nothing ever breaks.
interface OtCmd {
  type: "M" | "L" | "C" | "Q" | "Z";
  x?: number;
  y?: number;
  x1?: number;
  y1?: number;
  x2?: number;
  y2?: number;
}
type OtGlyphPath = { toPathData(fractionalDigits?: number): string; commands: OtCmd[] };
type OtFont = {
  getPath(t: string, x: number, y: number, size: number): OtGlyphPath;
  getAdvanceWidth(t: string, size: number): number;
};
const outlineFonts = new Map<string, OtFont>();

// `font-family="-x-google-Anton"` sources the outline from Google Fonts by name. The
// marker is stripped before compile (stripGooglePrefix) so layout, live <text>, and
// the outline lookup all see the bare family ("Anton").
const GOOGLE_PREFIX = "-x-google-";

// opentype.js parses ttf/otf/woff directly but *rejects* woff2 (the format Google's
// css2 API serves) — decompress woff2 → sfnt(ttf) first; anything else passes through.
const WOFF2_SIG = 0x774f4632; // 'wOF2'
async function toSfnt(buf: ArrayBuffer): Promise<ArrayBuffer> {
  if (buf.byteLength < 4 || new DataView(buf).getUint32(0) !== WOFF2_SIG) return buf;
  const { decompress } = await import("../vendor/woff2");
  const out = await decompress(new Uint8Array(buf));
  const u8 = out instanceof Uint8Array ? out : new Uint8Array(out);
  return u8.buffer.slice(u8.byteOffset, u8.byteOffset + u8.byteLength) as ArrayBuffer;
}

/** Register a font (by CSS family) for create-outlines, loaded from `url` (ttf/otf/woff/woff2). */
export async function registerOutlineFont(family: string, url: string): Promise<void> {
  const { parse } = await import("opentype.js");
  const bytes = await toSfnt(await (await fetch(url)).arrayBuffer());
  outlineFonts.set(family.toLowerCase(), parse(bytes) as OtFont);
  // Expose the same bytes as a live web font so plain <text> in this family renders
  // correctly too — not just the outlined <path>. Reuses the fetched bytes (no extra
  // request); a failure just leaves live text to fall back.
  await registerWebFont(family, bytes);
}

// Add `family` to the document's font set from raw sfnt bytes, so the browser can
// paint live <text font-family> and canvas `measureText` reports its real metrics.
// Loaded before compile (via ensureGoogleFont) so measurement sees the true font.
async function registerWebFont(family: string, sfnt: ArrayBuffer): Promise<void> {
  if (typeof FontFace === "undefined" || typeof document === "undefined") return;
  try {
    const face = new FontFace(family, sfnt);
    await face.load();
    document.fonts.add(face);
  } catch {
    /* live <text> falls back; the outlined <path> still carries the true face */
  }
}

// One in-flight registration per family, so concurrent/repeat compiles fetch once.
const pending = new Map<string, Promise<void>>();

// Resolve a Google-Fonts family to its outline. Idempotent and failure-tolerant: a
// network/parse failure is swallowed (the family stays unregistered → live <text>).
function ensureGoogleFont(family: string): Promise<void> {
  const key = family.toLowerCase();
  if (outlineFonts.has(key)) return Promise.resolve();
  let p = pending.get(key);
  if (!p) {
    p = (async () => {
      const css = await (
        await fetch(`https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}`)
      ).text();
      const url = pickLatinWoff2(css);
      if (!url) throw new Error("no usable @font-face in css2 response");
      await registerOutlineFont(family, url);
    })().catch((e) => {
      console.warn(`xsvg: Google font "${family}" could not be outlined —`, e);
    });
    pending.set(key, p);
  }
  return p;
}

// css2 returns one @font-face per unicode subset; pick the block covering Basic Latin
// (unicode-range U+0000-00FF), else the first woff2 url as a fallback.
function pickLatinWoff2(css: string): string | undefined {
  let first: string | undefined;
  for (const block of css.split("@font-face")) {
    const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    if (!url) continue;
    first ??= url;
    if (/U\+0000/.test(block)) return url;
  }
  return first;
}

// The distinct `-x-google-<Name>` families named by a source's font-family attributes.
function googleFamilies(source: string): string[] {
  const names = new Set<string>();
  for (const m of source.matchAll(/font-family\s*=\s*"([^"]*)"/g)) {
    for (const fam of m[1].split(",")) {
      const t = fam.trim().replace(/^['"]|['"]$/g, "");
      if (t.startsWith(GOOGLE_PREFIX)) names.add(t.slice(GOOGLE_PREFIX.length).trim());
    }
  }
  return [...names];
}

// Strip the marker inside font-family values so downstream sees the bare family.
function stripGooglePrefix(source: string): string {
  return source.replace(
    /font-family\s*=\s*"([^"]*)"/g,
    (_, v: string) => `font-family="${v.split(GOOGLE_PREFIX).join("")}"`,
  );
}

// The core hands us the resolved family verbatim (possibly a comma list) — key the
// outline lookup on the first family token.
function firstFamily(family: string): string {
  return family.split(",")[0].trim().replace(/^['"]|['"]$/g, "");
}

// A registered outline font for a (possibly comma-listed) CSS family, or undefined.
function lookupFont(family: string): OtFont | undefined {
  return outlineFonts.get(firstFamily(family).toLowerCase());
}

function outline(
  text: string,
  family: string,
  _weight: string,
  _style: string,
  size: number,
  x: number,
  baseline: number,
): string {
  const font = lookupFont(family);
  if (!font) return ""; // no bytes for this family → Rust keeps live <text>
  return font.getPath(text, x, baseline, size).toPathData(2);
}

// --- Text on a path (§6.13): the browser adapter for GlyphOutliner::outline_on_path.
// Outline the run on a flat baseline (opentype's structured commands), flatten to a
// tolerance, then push every vertex through a path-derived field — the §7 bake done in
// JS (the pure-Rust kurbo path is the later native impl). Fields: skew (§6.13.1 —
// vertical displacement by the path's height profile) and rainbow (§6.13.2 — arc-length
// follow + normal offset); baseline-shift offsets the run along the local normal.

// Sample a reference path as a height field f(x) — its y at horizontal position x
// (§6.13.1). Reuses the offscreen probe; assumes the path is single-valued in x.
// `x0`/`x1` are the path's start/end x — its extent for run placement (§6.13).
function pathHeightField(
  pathD: string,
): { x0: number; x1: number; y(x: number): number } | null {
  const p = probe();
  p.setAttribute("d", pathD);
  let len: number;
  try {
    len = p.getTotalLength();
  } catch {
    return null;
  }
  if (!(len > 0)) return null;
  const K = 256;
  const xs = new Float64Array(K + 1);
  const ys = new Float64Array(K + 1);
  for (let i = 0; i <= K; i++) {
    const pt = p.getPointAtLength((i / K) * len);
    xs[i] = pt.x;
    ys[i] = pt.y;
  }
  return {
    x0: xs[0],
    x1: xs[K],
    y(x: number): number {
      if (x <= xs[0]) return ys[0];
      if (x >= xs[K]) return ys[K];
      for (let i = 0; i < K; i++) {
        const a = xs[i];
        const b = xs[i + 1];
        if ((x >= a && x <= b) || (x <= a && x >= b)) {
          const t = b === a ? 0 : (x - a) / (b - a);
          return ys[i] + t * (ys[i + 1] - ys[i]);
        }
      }
      return ys[K];
    },
  };
}

// Sample a reference path as an arc-length frame (§6.13.2): `at(s, off)` is the point
// `off` units along the local normal from the path point at arc length `s`; `len` is
// the total arc length (the run-placement extent, §6.13). The normal is the tangent
// rotated +90° in y-down coords — for a left→right path it points down, so negative
// glyph y (ascenders) rises above the curve. Beyond either end the frame extends
// straight along the end tangent, so a run longer than the path continues rather than
// bunching up. Reuses the offscreen probe.
function pathArcFrame(
  pathD: string,
): { len: number; at(s: number, off: number): [number, number] } | null {
  const p = probe();
  p.setAttribute("d", pathD);
  let len: number;
  try {
    len = p.getTotalLength();
  } catch {
    return null;
  }
  if (!(len > 0)) return null;
  const K = 512;
  const xs = new Float64Array(K + 1);
  const ys = new Float64Array(K + 1);
  for (let i = 0; i <= K; i++) {
    const pt = p.getPointAtLength((i / K) * len);
    xs[i] = pt.x;
    ys[i] = pt.y;
  }
  // unit tangent of the LUT segment starting at sample i (degenerate → +x)
  const tangent = (i: number): [number, number] => {
    const dx = xs[i + 1] - xs[i];
    const dy = ys[i + 1] - ys[i];
    const d = Math.hypot(dx, dy);
    return d > 0 ? [dx / d, dy / d] : [1, 0];
  };
  const at = (s: number, off: number): [number, number] => {
    const sc = Math.min(Math.max(s, 0), len); // clamped arc position
    const over = s - sc; // straight-line overshoot past the path's ends
    const t = (sc / len) * K;
    const i = Math.min(K - 1, Math.floor(t));
    const frac = t - i;
    const [tx, ty] = tangent(i);
    const px = xs[i] + frac * (xs[i + 1] - xs[i]);
    const py = ys[i] + frac * (ys[i + 1] - ys[i]);
    return [px + over * tx - off * ty, py + over * ty + off * tx];
  };
  return { len, at };
}

// Where a run of width `w` begins within a path extent `E` (§6.13): `align`
// distributes the slack, `start` adds an absolute head-start. Slack may be negative
// (run longer than the path) — middle/end then shift before the start, symmetric with
// the past-the-end overshoot.
function runOffset(E: number, w: number, align: string, start: number): number {
  return start + (align === "middle" ? (E - w) / 2 : align === "end" ? E - w : 0);
}

// Flatten opentype glyph commands to closed contours (flat [x0,y0,x1,y1,…] arrays),
// no sub-segment longer than `step` (the graded quality knob).
function flattenGlyph(cmds: OtCmd[], step: number): number[][] {
  const contours: number[][] = [];
  let cur: number[] = [];
  let cx = 0;
  let cy = 0;
  let sx = 0;
  let sy = 0;
  const lineTo = (x: number, y: number) => {
    const n = Math.max(1, Math.ceil(Math.hypot(x - cx, y - cy) / step));
    for (let k = 1; k <= n; k++) cur.push(cx + ((x - cx) * k) / n, cy + ((y - cy) * k) / n);
    cx = x;
    cy = y;
  };
  for (const c of cmds) {
    if (c.type === "M") {
      if (cur.length) contours.push(cur);
      cur = [c.x!, c.y!];
      cx = sx = c.x!;
      cy = sy = c.y!;
    } else if (c.type === "L") {
      lineTo(c.x!, c.y!);
    } else if (c.type === "Q") {
      const x0 = cx;
      const y0 = cy;
      const n = Math.max(
        2,
        Math.ceil((Math.hypot(c.x1! - x0, c.y1! - y0) + Math.hypot(c.x! - c.x1!, c.y! - c.y1!)) / step),
      );
      for (let k = 1; k <= n; k++) {
        const t = k / n;
        const u = 1 - t;
        cur.push(
          u * u * x0 + 2 * u * t * c.x1! + t * t * c.x!,
          u * u * y0 + 2 * u * t * c.y1! + t * t * c.y!,
        );
      }
      cx = c.x!;
      cy = c.y!;
    } else if (c.type === "C") {
      const x0 = cx;
      const y0 = cy;
      const n = Math.max(
        2,
        Math.ceil(
          (Math.hypot(c.x1! - x0, c.y1! - y0) +
            Math.hypot(c.x2! - c.x1!, c.y2! - c.y1!) +
            Math.hypot(c.x! - c.x2!, c.y! - c.y2!)) /
            step,
        ),
      );
      for (let k = 1; k <= n; k++) {
        const t = k / n;
        const u = 1 - t;
        cur.push(
          u * u * u * x0 + 3 * u * u * t * c.x1! + 3 * u * t * t * c.x2! + t * t * t * c.x!,
          u * u * u * y0 + 3 * u * u * t * c.y1! + 3 * u * t * t * c.y2! + t * t * t * c.y!,
        );
      }
      cx = c.x!;
      cy = c.y!;
    } else if (c.type === "Z") {
      lineTo(sx, sy);
    }
  }
  if (cur.length) contours.push(cur);
  return contours;
}

function outlineOnPath(
  text: string,
  family: string,
  _weight: string,
  _style: string,
  size: number,
  pathD: string,
  effect: string,
  baselineShift: number,
  align: string,
  start: number,
): string {
  const font = lookupFont(family);
  if (!font) return ""; // no bytes → Rust falls back to live <text>
  const w = font.getAdvanceWidth(text, size); // run width for align (outline geometry
  // carries no letter/word-spacing, §6.12 — the extent slack must match it)
  // Per-effect vertex map — a §7.2 field. (gx, gy) are outline coords on the flat run
  // baseline (gy negative above it); baseline-shift lifts the run off the path.
  let map: (gx: number, gy: number) => [number, number];
  if (effect === "skew") {
    const field = pathHeightField(pathD);
    if (!field) return "";
    // skew field: (x, y) → (x, y + f(x)); align/start place the run in the x-extent
    const base = field.x0 + runOffset(field.x1 - field.x0, w, align, start);
    map = (gx, gy) => {
      const x = base + gx;
      return [x, field.y(x) + gy - baselineShift];
    };
  } else if (effect === "rainbow") {
    const frame = pathArcFrame(pathD);
    if (!frame) return "";
    // path-follow field: (x, y) → P(s) + y·N(s); align/start place s in the arc length
    const base = runOffset(frame.len, w, align, start);
    map = (gx, gy) => frame.at(base + gx, gy - baselineShift);
  } else {
    return ""; // unknown effect → graceful live-<text> fallback
  }
  const step = Math.max(1, size / 12); // flatten tolerance, size-relative (quality knob)
  const contours = flattenGlyph(font.getPath(text, 0, 0, size).commands, step);
  const r = (n: number) => (Math.round(n * 100) / 100).toString();
  let d = "";
  for (const c of contours) {
    for (let i = 0; i < c.length; i += 2) {
      const [x, y] = map(c[i], c[i + 1]);
      // totality (§4): a degenerate path/field must never leak NaN/inf coordinates —
      // abandon the warp and let Rust fall back to live <text>
      if (!(Number.isFinite(x) && Number.isFinite(y))) return "";
      d += (i === 0 ? "M" : "L") + r(x) + "," + r(y);
    }
    d += "Z";
  }
  return d;
}

// Stepped-baseline sampler (§6.13.1 degradation) — the browser adapter for
// Shaper::baseline_samples. `advances` holds each glyph's x-offset from the run
// origin plus a final total-width entry; returns [runStartX, y0 … y(n-1)] with the
// run placed by align/start in the path's x-extent, or an empty array on failure
// (→ straight-text fallback). Non-finite samples abort — never leak NaN (§4).
function steppedBaseline(
  pathD: string,
  advances: Float64Array,
  align: string,
  start: number,
): Float64Array {
  const n = advances.length - 1;
  const field = n >= 1 ? pathHeightField(pathD) : null;
  if (!field) return new Float64Array(0);
  const x0 = field.x0 + runOffset(field.x1 - field.x0, advances[n], align, start);
  const out = new Float64Array(n + 1);
  out[0] = x0;
  for (let i = 0; i < n; i++) {
    const y = field.y(x0 + advances[i]);
    if (!Number.isFinite(y)) return new Float64Array(0);
    out[i + 1] = y;
  }
  return out;
}

export interface CompileOptions {
  /** Quality profile string (default "balanced"). */
  quality?: string;
  /**
   * Emit `data-xsvg-pos="START-END"` byte-range attributes on every top-level
   * element so a viewer can project a rendered element back to its xsvg source.
   * Off by default (keeps embed output clean).
   */
  sourcemap?: boolean;
}

/** Compile an xsvg source string to a plain-SVG string (runs entirely client-side). */
export async function compileXsvg(source: string, opts: CompileOptions = {}): Promise<string> {
  await ensureReady();
  // Resolve any `-x-google-<Name>` outline fonts up front (a miss is swallowed), then
  // strip the marker so the compiler only ever sees bare family names.
  await Promise.all(googleFamilies(source).map(ensureGoogleFont));
  source = stripGooglePrefix(source);
  const { quality = "balanced", sourcemap = false } = opts;
  return compile(
    source,
    quality,
    sourcemap,
    measure,
    metrics,
    rasterize,
    steppedBaseline,
    outline,
    outlineOnPath,
  );
}
