// Thin TS wrapper over the Rust→WASM compiler.
// The WASM module is initialized once, lazily; every call awaits readiness.
//
// `../pkg/` is generated by `wasm-pack` (see `npm run wasm:dev`). Until you have
// run a build at least once, the editor will not find these types — that's
// expected; `npm run dev` builds the wasm before starting Vite.
import init, { compile } from "../pkg/xsvg_wasm.js";

let ready: Promise<unknown> | null = null;

function ensureReady(): Promise<unknown> {
  if (!ready) ready = init();
  return ready;
}

// Font metrics for text layout — the browser implementation of the core's
// `Measurer` seam. The Rust compiler calls this back synchronously during
// lowering (e.g. for `inline-size` wrapping and `<x:textbox>` shrink-to-fit).
let measureCtx: CanvasRenderingContext2D | null = null;
function ctx(): CanvasRenderingContext2D | null {
  if (!measureCtx) measureCtx = document.createElement("canvas").getContext("2d");
  return measureCtx;
}

function measure(text: string, fontCss: string): number {
  const c = ctx();
  if (!c) return 0;
  c.font = fontCss;
  return c.measureText(text).width;
}

// Vertical font metrics at the given font: [ascent, descent, capHeight, xHeight].
function metrics(fontCss: string): number[] {
  const c = ctx();
  if (!c) return [];
  c.font = fontCss;
  const box = c.measureText("Hg");
  const cap = c.measureText("H");
  const ex = c.measureText("x");
  return [
    box.fontBoundingBoxAscent,
    box.fontBoundingBoxDescent,
    cap.actualBoundingBoxAscent,
    ex.actualBoundingBoxAscent,
  ];
}

// Shape rasterizer — the browser implementation of the core's `Shaper` seam, used
// by `<x:textbox in="#shape">` to flow text inside a curved outline. Curve
// flattening + inside-testing are deferred to the browser (`getBBox` +
// `isPointInFill`) on a hidden offscreen <svg> probe.
const SVG_NS = "http://www.w3.org/2000/svg";
let probePath: SVGPathElement | null = null;
function probe(): SVGPathElement {
  if (!probePath) {
    const svg = document.createElementNS(SVG_NS, "svg");
    // rendered but off-screen: getBBox needs layout (display:none returns zeros)
    svg.setAttribute("style", "position:absolute;left:-99999px;top:0;overflow:hidden");
    probePath = document.createElementNS(SVG_NS, "path");
    svg.appendChild(probePath);
    document.body.appendChild(svg);
  }
  return probePath;
}

// Rasterize a filled path `d` into [minX, minY, w, h, rowH, l0,r0, l1,r1, …] — one
// inside [left,right] span per ~rowH-tall row (NaN pair if that row is empty).
// Exported so the fixture generator (fixtures.ts) can reuse the exact browser path.
export function rasterize(d: string, rowH: number): number[] {
  const p = probe();
  p.setAttribute("d", d);
  let bb: DOMRect;
  try {
    bb = p.getBBox();
  } catch {
    return [];
  }
  if (!(bb.width > 0 && bb.height > 0 && rowH > 0)) return [];

  const rows = Math.max(1, Math.ceil(bb.height / rowH));
  const rh = bb.height / rows;
  const xSteps = Math.max(24, Math.min(400, Math.ceil(bb.width)));
  const dx = bb.width / xSteps;
  const out: number[] = [bb.x, bb.y, bb.width, bb.height, rh];
  const pt = new DOMPoint(0, 0);

  for (let r = 0; r < rows; r++) {
    pt.y = bb.y + (r + 0.5) * rh;
    let left = NaN;
    let right = NaN;
    for (let i = 0; i <= xSteps; i++) {
      pt.x = bb.x + i * dx;
      if (p.isPointInFill(pt)) {
        if (Number.isNaN(left)) left = pt.x;
        right = pt.x;
      }
    }
    out.push(left, right);
  }
  return out;
}

/** Compile an xsvg source string to a plain-SVG string (runs entirely client-side). */
export async function compileXsvg(source: string, quality = "balanced"): Promise<string> {
  await ensureReady();
  return compile(source, quality, measure, metrics, rasterize);
}
