// Thin TS wrapper over the Rust→WASM compiler.
// The WASM module is initialized once, lazily; every call awaits readiness.
//
// `../pkg/` is generated by `wasm-pack` (see `npm run wasm:dev`). Until you have
// run a build at least once, the editor will not find these types — that's
// expected; `npm run dev` builds the wasm before starting Vite.
import init, { compile } from "../pkg/xsvg_wasm.js";

let ready: Promise<unknown> | null = null;

function ensureReady(): Promise<unknown> {
  if (!ready) ready = init();
  return ready;
}

/** Compile an xsvg source string to a plain-SVG string (runs entirely client-side). */
export async function compileXsvg(source: string, quality = "balanced"): Promise<string> {
  await ensureReady();
  return compile(source, quality);
}
