// Thin TS wrapper over the Rust→WASM compiler — the one compile core shared by the
// embed, the interactive viewer, and the playground.
//
// The WASM module is initialized once. Two init paths share the single module:
//   • ensureReady()      — the apps: lazy async init(), fetching the sibling .wasm
//                          asset Vite emits (new URL('..._bg.wasm', import.meta.url)).
//   • initFromBytes(b)   — the single-file embed: synchronous init from WASM bytes
//                          inlined into the bundle, so no extra network request runs.
//
// `../../pkg/` is generated by `wasm-pack` (see `npm run wasm:dev`). Until you have
// run a build at least once, the editor will not find these types — that's expected.
import init, { compile, initSync } from "../pkg/xsvg_wasm.js";

let ready: Promise<unknown> | null = null;

function ensureReady(): Promise<unknown> {
  if (!ready) ready = init();
  return ready;
}

/**
 * Pre-initialize the WASM synchronously from raw module bytes. Used by the embed
 * bundle, which inlines the `.wasm` so a single `<script>` is fully self-contained.
 * A no-op if the module is already initialized.
 */
export function initFromBytes(bytes: Uint8Array): void {
  if (ready) return;
  initSync({ module: bytes });
  ready = Promise.resolve();
}

// Font metrics for text layout — the browser implementation of the core's
// `Measurer` seam. The Rust compiler calls this back synchronously during
// lowering (e.g. for `inline-size` wrapping and `<x:textbox>` shrink-to-fit).
let measureCtx: CanvasRenderingContext2D | null = null;
function ctx(): CanvasRenderingContext2D | null {
  if (!measureCtx) measureCtx = document.createElement("canvas").getContext("2d");
  return measureCtx;
}

function measure(text: string, fontCss: string): number {
  const c = ctx();
  if (!c) return 0;
  c.font = fontCss;
  return c.measureText(text).width;
}

// Vertical font metrics at the given font: [ascent, descent, capHeight, xHeight].
function metrics(fontCss: string): number[] {
  const c = ctx();
  if (!c) return [];
  c.font = fontCss;
  const box = c.measureText("Hg");
  const cap = c.measureText("H");
  const ex = c.measureText("x");
  return [
    box.fontBoundingBoxAscent,
    box.fontBoundingBoxDescent,
    cap.actualBoundingBoxAscent,
    ex.actualBoundingBoxAscent,
  ];
}

// Shape rasterizer — the browser implementation of the core's `Shaper` seam, used
// by `<x:textbox in="#shape">` to flow text inside a curved outline. Curve
// flattening + inside-testing are deferred to the browser (`getBBox` +
// `isPointInFill`) on a hidden offscreen <svg> probe.
const SVG_NS = "http://www.w3.org/2000/svg";
let probePath: SVGPathElement | null = null;
function probe(): SVGPathElement {
  if (!probePath) {
    const svg = document.createElementNS(SVG_NS, "svg");
    // rendered but off-screen: getBBox needs layout (display:none returns zeros)
    svg.setAttribute("style", "position:absolute;left:-99999px;top:0;overflow:hidden");
    probePath = document.createElementNS(SVG_NS, "path");
    svg.appendChild(probePath);
    document.body.appendChild(svg);
  }
  return probePath;
}

// Rasterize a filled path `d` into [minX, minY, w, h, rowH, l0,r0, l1,r1, …] — one
// inside [left,right] span per ~rowH-tall row (NaN pair if that row is empty).
// Exported so the fixture generator (dev/fixtures.ts) can reuse the exact browser path.
export function rasterize(d: string, rowH: number): number[] {
  const p = probe();
  p.setAttribute("d", d);
  let bb: DOMRect;
  try {
    bb = p.getBBox();
  } catch {
    return [];
  }
  if (!(bb.width > 0 && bb.height > 0 && rowH > 0)) return [];

  const rows = Math.max(1, Math.ceil(bb.height / rowH));
  const rh = bb.height / rows;
  const xSteps = Math.max(24, Math.min(400, Math.ceil(bb.width)));
  const dx = bb.width / xSteps;
  const out: number[] = [bb.x, bb.y, bb.width, bb.height, rh];
  const pt = new DOMPoint(0, 0);

  for (let r = 0; r < rows; r++) {
    pt.y = bb.y + (r + 0.5) * rh;
    let left = NaN;
    let right = NaN;
    for (let i = 0; i <= xSteps; i++) {
      pt.x = bb.x + i * dx;
      if (p.isPointInFill(pt)) {
        if (Number.isNaN(left)) left = pt.x;
        right = pt.x;
      }
    }
    out.push(left, right);
  }
  return out;
}

// Glyph outliner — the browser implementation of the core's `GlyphOutliner` seam.
// "Create outlines" (`x:outline`/`outline="true"`) turns a text run into a <path>;
// opentype.js needs the font *bytes*, keyed by family. A family with no registered
// font returns "" → the compiler falls back to live <text>, so nothing ever breaks.
type OtGlyphPath = { toPathData(fractionalDigits?: number): string };
type OtFont = {
  getPath(t: string, x: number, y: number, size: number): OtGlyphPath;
  getAdvanceWidth(t: string, size: number): number;
};
const outlineFonts = new Map<string, OtFont>();

// `font-family="-x-google-Anton"` sources the outline from Google Fonts by name. The
// marker is stripped before compile (stripGooglePrefix) so layout, live <text>, and
// the outline lookup all see the bare family ("Anton").
const GOOGLE_PREFIX = "-x-google-";

// opentype.js parses ttf/otf/woff directly but *rejects* woff2 (the format Google's
// css2 API serves) — decompress woff2 → sfnt(ttf) first; anything else passes through.
const WOFF2_SIG = 0x774f4632; // 'wOF2'
async function toSfnt(buf: ArrayBuffer): Promise<ArrayBuffer> {
  if (buf.byteLength < 4 || new DataView(buf).getUint32(0) !== WOFF2_SIG) return buf;
  const { decompress } = await import("./vendor/woff2");
  const out = await decompress(new Uint8Array(buf));
  const u8 = out instanceof Uint8Array ? out : new Uint8Array(out);
  return u8.buffer.slice(u8.byteOffset, u8.byteOffset + u8.byteLength) as ArrayBuffer;
}

/** Register a font (by CSS family) for create-outlines, loaded from `url` (ttf/otf/woff/woff2). */
export async function registerOutlineFont(family: string, url: string): Promise<void> {
  const { parse } = await import("opentype.js");
  const bytes = await toSfnt(await (await fetch(url)).arrayBuffer());
  outlineFonts.set(family.toLowerCase(), parse(bytes) as OtFont);
  // Expose the same bytes as a live web font so plain <text> in this family renders
  // correctly too — not just the outlined <path>. Reuses the fetched bytes (no extra
  // request); a failure just leaves live text to fall back.
  await registerWebFont(family, bytes);
}

// Add `family` to the document's font set from raw sfnt bytes, so the browser can
// paint live <text font-family> and canvas `measureText` reports its real metrics.
// Loaded before compile (via ensureGoogleFont) so measurement sees the true font.
async function registerWebFont(family: string, sfnt: ArrayBuffer): Promise<void> {
  if (typeof FontFace === "undefined" || typeof document === "undefined") return;
  try {
    const face = new FontFace(family, sfnt);
    await face.load();
    document.fonts.add(face);
  } catch {
    /* live <text> falls back; the outlined <path> still carries the true face */
  }
}

// One in-flight registration per family, so concurrent/repeat compiles fetch once.
const pending = new Map<string, Promise<void>>();

// Resolve a Google-Fonts family to its outline. Idempotent and failure-tolerant: a
// network/parse failure is swallowed (the family stays unregistered → live <text>).
function ensureGoogleFont(family: string): Promise<void> {
  const key = family.toLowerCase();
  if (outlineFonts.has(key)) return Promise.resolve();
  let p = pending.get(key);
  if (!p) {
    p = (async () => {
      const css = await (
        await fetch(`https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}`)
      ).text();
      const url = pickLatinWoff2(css);
      if (!url) throw new Error("no usable @font-face in css2 response");
      await registerOutlineFont(family, url);
    })().catch((e) => {
      console.warn(`xsvg: Google font "${family}" could not be outlined —`, e);
    });
    pending.set(key, p);
  }
  return p;
}

// css2 returns one @font-face per unicode subset; pick the block covering Basic Latin
// (unicode-range U+0000-00FF), else the first woff2 url as a fallback.
function pickLatinWoff2(css: string): string | undefined {
  let first: string | undefined;
  for (const block of css.split("@font-face")) {
    const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    if (!url) continue;
    first ??= url;
    if (/U\+0000/.test(block)) return url;
  }
  return first;
}

// The distinct `-x-google-<Name>` families named by a source's font-family attributes.
function googleFamilies(source: string): string[] {
  const names = new Set<string>();
  for (const m of source.matchAll(/font-family\s*=\s*"([^"]*)"/g)) {
    for (const fam of m[1].split(",")) {
      const t = fam.trim().replace(/^['"]|['"]$/g, "");
      if (t.startsWith(GOOGLE_PREFIX)) names.add(t.slice(GOOGLE_PREFIX.length).trim());
    }
  }
  return [...names];
}

// Strip the marker inside font-family values so downstream sees the bare family.
function stripGooglePrefix(source: string): string {
  return source.replace(
    /font-family\s*=\s*"([^"]*)"/g,
    (_, v: string) => `font-family="${v.split(GOOGLE_PREFIX).join("")}"`,
  );
}

// The core hands us the resolved family verbatim (possibly a comma list) — key the
// outline lookup on the first family token.
function firstFamily(family: string): string {
  return family.split(",")[0].trim().replace(/^['"]|['"]$/g, "");
}

// A registered outline font for a (possibly comma-listed) CSS family, or undefined.
function lookupFont(family: string): OtFont | undefined {
  return outlineFonts.get(firstFamily(family).toLowerCase());
}

function outline(
  text: string,
  family: string,
  _weight: string,
  _style: string,
  size: number,
  x: number,
  baseline: number,
): string {
  const font = lookupFont(family);
  if (!font) return ""; // no bytes for this family → Rust keeps live <text>
  let d = font.getPath(text, x, baseline, size).toPathData(2);
  // opentype.js v2 emits no explicit close commands — glyph contours are only
  // *implicitly* closed (last point ≈ the subpath's M). Fill doesn't care, but
  // an outline STROKE (a bordered/keyline glyph) shows an open gap. Close each
  // subpath ourselves: a Z before every M after the first, and one at the end.
  if (d && !d.includes("Z")) d = d.replace(/M/g, (_m, i) => (i === 0 ? "M" : "ZM")) + "Z";
  return d;
}

// Advance width of a run per the outline font's own metrics — the browser adapter
// for GlyphOutliner::advance_width. NaN when the family has no registered bytes
// (→ Rust degrades). All §6.13 path-warp math itself runs natively in xsvg-core.
function advanceWidth(
  text: string,
  family: string,
  _weight: string,
  _style: string,
  size: number,
): number {
  const font = lookupFont(family);
  return font ? font.getAdvanceWidth(text, size) : NaN;
}

export interface CompileOptions {
  /** Quality profile string (default "balanced"). */
  quality?: string;
  /**
   * Emit `data-xsvg-pos="START-END"` byte-range attributes on every top-level
   * element so a viewer can project a rendered element back to its xsvg source.
   * Off by default (keeps embed output clean).
   */
  sourcemap?: boolean;
}

/** Compile an xsvg source string to a plain-SVG string (runs entirely client-side). */
export async function compileXsvg(source: string, opts: CompileOptions = {}): Promise<string> {
  await ensureReady();
  // Resolve any `-x-google-<Name>` outline fonts up front (a miss is swallowed), then
  // strip the marker so the compiler only ever sees bare family names.
  await Promise.all(googleFamilies(source).map(ensureGoogleFont));
  source = stripGooglePrefix(source);
  const { quality = "balanced", sourcemap = false } = opts;
  return compile(source, quality, sourcemap, measure, metrics, rasterize, outline, advanceWidth);
}
